**NUMPY & PANDAS**

**Basic or fundamental of NUMPY**

In [ ]:
import math #math is the library
from math import sqrt #sqrt is the module

In [ ]:
sqrt(25)

5.0

In [ ]:
from math import * #all the modules within math library will be made functional.

In [ ]:
sqrt(361)

19.0

In [ ]:
sin(25)

-0.13235175009777303

In [ ]:
cos(20)

0.40808206181339196

**Numpy**

In [ ]:
import numpy as np #np is the alias name

In [ ]:
my_list=[2,3,4,5,6]

In [ ]:
type(my_list)

list

In [ ]:
arr=np.array(my_list)

In [ ]:
print(arr) #1D array

[2 3 4 5 6]


In [ ]:
type(arr)

numpy.ndarray

In [ ]:
my_list_1=[2,6,8,12,0]
my_list_2=[3,4,-2,5,6]
my_list_3=[0,11,4,9,6]

arr_new=np.array([my_list_1,my_list_2,my_list_3])

In [ ]:
print(arr_new) #multinested aaray or 2D array

[[ 2  6  8 12  0]
 [ 3  4 -2  5  6]
 [ 0 11  4  9  6]]


In [ ]:
arr_new.shape

(3, 5)

In [ ]:
 arr_new.reshape(5,3)

array([[ 2,  6,  8],
       [12,  0,  3],
       [ 4, -2,  5],
       [ 6,  0, 11],
       [ 4,  9,  6]])

In [ ]:
a=np.arange(0,20,3) #equally spaced values in a given range

In [ ]:
print(a)

[ 0  3  6  9 12 15 18]


In [ ]:
np.linspace(1,10,50) #50 denotes the number of elements desired in the given range

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [ ]:
np.linspace(1,10,70) #70 denotes the number of elements desired in the given range

array([ 1.        ,  1.13043478,  1.26086957,  1.39130435,  1.52173913,
        1.65217391,  1.7826087 ,  1.91304348,  2.04347826,  2.17391304,
        2.30434783,  2.43478261,  2.56521739,  2.69565217,  2.82608696,
        2.95652174,  3.08695652,  3.2173913 ,  3.34782609,  3.47826087,
        3.60869565,  3.73913043,  3.86956522,  4.        ,  4.13043478,
        4.26086957,  4.39130435,  4.52173913,  4.65217391,  4.7826087 ,
        4.91304348,  5.04347826,  5.17391304,  5.30434783,  5.43478261,
        5.56521739,  5.69565217,  5.82608696,  5.95652174,  6.08695652,
        6.2173913 ,  6.34782609,  6.47826087,  6.60869565,  6.73913043,
        6.86956522,  7.        ,  7.13043478,  7.26086957,  7.39130435,
        7.52173913,  7.65217391,  7.7826087 ,  7.91304348,  8.04347826,
        8.17391304,  8.30434783,  8.43478261,  8.56521739,  8.69565217,
        8.82608696,  8.95652174,  9.08695652,  9.2173913 ,  9.34782609,
        9.47826087,  9.60869565,  9.73913043,  9.86956522, 10.  

In [ ]:
np.linspace(1,10,30) #30 denotes the number of elements desired in the given range

array([ 1.        ,  1.31034483,  1.62068966,  1.93103448,  2.24137931,
        2.55172414,  2.86206897,  3.17241379,  3.48275862,  3.79310345,
        4.10344828,  4.4137931 ,  4.72413793,  5.03448276,  5.34482759,
        5.65517241,  5.96551724,  6.27586207,  6.5862069 ,  6.89655172,
        7.20689655,  7.51724138,  7.82758621,  8.13793103,  8.44827586,
        8.75862069,  9.06896552,  9.37931034,  9.68965517, 10.        ])

generating random numbers

In [ ]:
np.random.rand(3,4) #here 3 indicates the number of rows and 4 indicates the number of colums
#by default the range is between 0-1, 1 being exclusive in nature
#numbers generated are floating point numbers

array([[0.15737156, 0.69774101, 0.55222492, 0.55838774],
       [0.99064418, 0.10502909, 0.43266626, 0.12820158],
       [0.86103676, 0.49719094, 0.41607964, 0.07043339]])

In [ ]:
np.random.randint(1,20,5) #5 denotes the number random elements we want in the given range
#numbers generated are integers

array([18, 12, 10, 13,  2])

In [ ]:
np.random.randint(1,20,size=(2,3)) #it will fetch 2D array type numbers

array([[ 4, 12, 14],
       [16, 18, 13]])

**Pandas**

In [ ]:
import pandas as pd #pd is the alias name

In [ ]:
data=pd.read_csv('/content/tips.csv') #reading the data

In [ ]:
data.head() #bydefault the first 5 rows of the dataset will be displayed

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [ ]:
data.head(10) #first 10 rows will be displayed

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4
5       25.29  4.71    Male     No  Sun  Dinner     4
6        8.77  2.00    Male     No  Sun  Dinner     2
7       26.88  3.12    Male     No  Sun  Dinner     4
8       15.04  1.96    Male     No  Sun  Dinner     2
9       14.78  3.23    Male     No  Sun  Dinner     2

In [ ]:
data.tail()  #bydefault the last 5 rows of the dataset will be displayed

total_bill   tip     sex smoker   day    time  size
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

In [ ]:
data.tail(15) #last 15 rows will be displayed

total_bill   tip     sex smoker   day    time  size
229       22.12  2.88  Female    Yes   Sat  Dinner     2
230       24.01  2.00    Male    Yes   Sat  Dinner     4
231       15.69  3.00    Male    Yes   Sat  Dinner     3
232       11.61  3.39    Male     No   Sat  Dinner     2
233       10.77  1.47    Male     No   Sat  Dinner     2
234       15.53  3.00    Male    Yes   Sat  Dinner     2
235       10.07  1.25    Male     No   Sat  Dinner     2
236       12.60  1.00    Male    Yes   Sat  Dinner     2
237       32.83  1.17    Male    Yes   Sat  Dinner     2
238       35.83  4.67  Female     No   Sat  Dinner     3
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

In [ ]:
data.info() #it will fetch general information

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    object 
 3   smoker      244 non-null    object 
 4   day         244 non-null    object 
 5   time        244 non-null    object 
 6   size        244 non-null    int64  
dtypes: float64(2), int64(1), object(4)
memory usage: 13.5+ KB


In [ ]:
data.describe() #it will fetch statistical information

total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

**Create a dummy dataset**

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
my_data=pd.DataFrame(np.arange(0,20).reshape(5,4),index=['row1','row2','row3','row4','row5'],columns=['col1','col2','col3','col4'])

In [ ]:
print(my_data)

      col1  col2  col3  col4
row1     0     1     2     3
row2     4     5     6     7
row3     8     9    10    11
row4    12    13    14    15
row5    16    17    18    19


**indexing slicing with dataset**

In [ ]:
#iloc[]
my_data.iloc[2:4,2:]

col3  col4
row3    10    11
row4    14    15

In [ ]:
my_data.iloc[:,:]

col1  col2  col3  col4
row1     0     1     2     3
row2     4     5     6     7
row3     8     9    10    11
row4    12    13    14    15
row5    16    17    18    19

**Export or Download**

In [ ]:
my_data.to_csv('my_data.csv') #download for csv file

my_data.to_excel('my_data.xlsx') #download for excel file